### ISSUE TITLE
improvement for EGI

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace-egi#4]
1. Change Copyright 2021 to Copyright 2022
2. Contact us should redirect to https://www.egi.eu/contact/
3. Change address in Store information to:
The EGI Foundation
Science Park 140
1098 XG Amsterdam
The Netherlands
4. Change  “Term od Conditions” to “Terms of Use”
5. Change "Coorporate Level Service Level Agreement (SLA)" to "Coorporate Service Level Agreement (SLA)" (https://beta.marketplace.egi.eu/sla)

**Comment by kmarszalek** [comment]
[tag-egi-v1.0.4-mp-v3.36.0](https://github.com/cyfronet-fid/marketplace/tree/tag-egi-v1.0.4-mp-v3.36.0)
