### ISSUE TITLE
Make signature in testimonials more visible

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace-egi#8]
![image](https://user-images.githubusercontent.com/59872096/162219158-10866d56-e3df-4156-b076-f01ef617305d.png)

Signature should be aligned to the right INSIDE the respective boxes

**Comment by kmarszalek** [comment]
[tag-egi-v1.0.4-mp-v3.36.0](https://github.com/cyfronet-fid/marketplace/tree/tag-egi-v1.0.4-mp-v3.36.0)
